public class BooleanData{
    
    public void myboolean(){
    
    boolean isLeapYear = false;
        
        if(isLeapYear){
            
            
            System.debug('it is a leap year');
    }
        else{
          system.debug('its not a leap year'); 
            
            
          }
        
   if ('Hello'.endsWith('o')) {
System.debug('me');
System.debug('me too!');
}     
if (4 > 2) System.debug ('Yep, 4 is greater than 2');        
            }
    }